import { useEffect, useState } from "react";
import { Bot } from "lucide-react";
import { Button } from "./ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "./ui/card";
import { Label } from "./ui/label";
import { SettingsLayout } from "./SettingsLayout";

type SessionDefaults = { provider: string; modelId: string; thinkingLevel: string };
type SessionDefaultModel = { provider: string; modelId: string; displayName?: string };
const thinkingLevels = ["off", "minimal", "low", "medium", "high", "xhigh", "max"];
const modelValue = (model: Pick<SessionDefaultModel, "provider" | "modelId">): string => JSON.stringify([model.provider, model.modelId]);
export function SessionDefaultsPage({ onBack }: { onBack: () => void }) {
  const [defaults, setDefaults] = useState<SessionDefaults>(); const [models, setModels] = useState<readonly SessionDefaultModel[]>([]); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  useEffect(() => { void fetch("/v2/session-defaults", { cache: "no-store", headers: { Accept: "application/json" } }).then(async (response) => { if (!response.ok) throw new Error(); return response.json() as Promise<{ defaults: SessionDefaults; models?: readonly SessionDefaultModel[] }>; }).then((body) => { setDefaults(body.defaults); setModels(body.models ?? []); }).catch(() => setMessage("Session defaults could not be loaded.")); }, []);
  const save = async (): Promise<void> => { if (defaults === undefined || models.length === 0) return; setBusy(true); setMessage(""); try { const response = await fetch("/v2/session-defaults", { method: "PUT", headers: { "Content-Type": "application/json", Accept: "application/json" }, body: JSON.stringify(defaults) }); if (!response.ok) throw new Error(); const body = await response.json() as { defaults: SessionDefaults }; setDefaults(body.defaults); setMessage("Defaults saved."); } catch { setMessage("Session defaults could not be saved."); } finally { setBusy(false); } };
  const selectedModelAvailable = defaults !== undefined && models.some((model) => model.provider === defaults.provider && model.modelId === defaults.modelId);
  return <SettingsLayout title="Session Defaults" description="Choose defaults for new Sessions." onBack={onBack}><Card className="settings-card bg-transparent"><CardHeader><CardTitle><Bot aria-hidden="true" /> New Sessions</CardTitle><CardDescription>Existing and opened Sessions keep their own settings. Delegated Sessions inherit their parent Session settings.</CardDescription></CardHeader><CardContent>{defaults && <div className="settings-form"><div className="settings-field"><Label htmlFor="default-model">Model</Label><select id="default-model" className="settings-select" value={modelValue(defaults)} disabled={models.length === 0} onChange={(event) => { const selected = JSON.parse(event.target.value) as [string, string]; setDefaults({ ...defaults, provider: selected[0], modelId: selected[1] }); }}>{!selectedModelAvailable && <option value={modelValue(defaults)} disabled>{defaults.modelId} · {defaults.provider} (unavailable)</option>}{models.map((model) => <option key={modelValue(model)} value={modelValue(model)}>{model.displayName ?? model.modelId} · {model.provider}</option>)}</select></div><div className="settings-field"><Label htmlFor="thinking-level">Thinking level</Label><select id="thinking-level" className="settings-select" value={defaults.thinkingLevel} onChange={(event) => setDefaults({ ...defaults, thinkingLevel: event.target.value })}>{thinkingLevels.map((level) => <option key={level} value={level}>{level[0]?.toUpperCase()}{level.slice(1)}</option>)}</select></div><Button disabled={busy || models.length === 0 || !selectedModelAvailable} type="button" onClick={() => void save()}>Save defaults</Button></div>}{defaults !== undefined && models.length === 0 && <p role="status" className="settings-message">No authenticated models are available.</p>}{message && <p role="status" className="settings-message">{message}</p>}</CardContent></Card></SettingsLayout>;
}
